export enum types_color_enum {
    bug = "#A8B820",
    dark= "#705848",
    dragon= "#7038F8",
    electric= "#F8D030",
    fairy= "#EE99AC",
    fighting= "#C03028",
    flying= "#A890F0",
    ghost= "#705898",
    ground= "#E0C068",
    normal= "#705848",
    grass="#78C850" ,
    fire= "#E24242",
    poison= "#A040A0",
    psychic= "#F85888",
    rock= "#B8A038",
    steel= "#B8B8D0",
    ice="#98D8D8",
    water="#6890F0"
}

export enum pokemon_types {
    all='all',
    bug='bug',
    dark='dark',
    dragon='dragon',
    electric='electric',
    fairy='fairy',
    fighting='fighting',
    flying='flying',
    ghost='ghost',
    ground='ground',
    normal='normal',
    grass='grass',
    fire='fire',
    poison='poison',
    psychic='psychic',
    rock='rock',
    steel='steel',
    ice='ice',
    water='water'
}
